# Generated by Django 2.1.4 on 2020-01-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(verbose_name='滑动者')),
                ('target_id', models.IntegerField(verbose_name='被滑者')),
                ('type', models.CharField(choices=[('like', '左滑喜欢'), ('superlike', '右滑超级喜欢'), ('unlike', '上滑不喜欢')], max_length=20, verbose_name='滑动类型')),
                ('s_time', models.DateTimeField(auto_now_add=True, verbose_name='滑动时间')),
            ],
        ),
    ]
